### PR TITLE
fix(doc): Fix typo on README file

### PR DESCRIPTION
**Pull request by Atternatt**

### CODE REVIEW

**Comment by Atternatt** [comment]
@uberto I hope you don't mind I fixed a small typo in the main document :) (IDK why I cant add you as reviewer)

**Review by uberto — APPROVED** [review]

**Comment by uberto** [comment]
Thanks! Approved

Uberto

**Comment by Atternatt** [comment]
@uberto I think you have to merge it. It doesn't allow me to do it :)

**Comment by uberto** [comment]
done. :)

**Pull request merged**
